### ISSUE TITLE
Augment metadata server stats

### ISSUE THREAD

**Issue by arhamahmed** [kurafs/kura#6]
Include the following (ensure encrypted):
- essentially everything `stat` returns for a file
- storage servers the file was replicated to
- emails of people the file was shared with
- permissions of the people the file was shared with
.
.
.

**Comment by Dendrimer** [comment]
This might have some dependencies on what @irfansharif is working on, since he's doing key sharing.

**Comment by irfansharif** [comment]
RIP Kura (2018 - 2019).
